

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Named volume
      - ./postgres/sql/init/init_ddl.sql:/docker-entrypoint-initdb.d/init_ddl.sql
      - ./postgres/sql/init/init_dml.sql:/docker-entrypoint-initdb.d/init_dml.sql
    restart: always

  etl-service:
    build: ./etl-service
    depends_on:
      - postgres
    volumes:
      - ./etl-service/data:/app/data
    ports:
      - "5000:5000"
    restart: always

  webapi-service:
    build: ./webapi-service
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=dwh;Username=airflow;Password=airflow
    ports:
      - "5163:5163"
    depends_on:
      - postgres
    volumes:
      - webapi_data:/app/src  # Named volume

  # airflow:
  #   build: ./airflow
  #   depends_on:
  #     - postgres
  #     - etl_service
  #   environment:
  #     - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  #     - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://user:password@postgres:5432/airflow_db
  #   volumes:
  #     - ./dags:/opt/airflow/dags
  #   ports:
  #     - "8080:8080"
  #   command: webserver

volumes:
  postgres_data:  # Define named volume
  webapi_data:  # Define named volume