// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Persistence;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250329134027_InitialLoad")]
    partial class InitialLoad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("webapi.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Customer_Id");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT")
                        .HasColumnName("Country");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("InsertedDate");

                    b.Property<string>("InsertedUser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("UpdatedDate");

                    b.Property<string>("UpdatedUser")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Country = "Undefined",
                            CustomerId = "Undefined",
                            InsertedDate = new DateTime(2025, 3, 29, 14, 40, 27, 801, DateTimeKind.Local).AddTicks(2160),
                            InsertedUser = "SYSTEM",
                            UpdatedDate = new DateTime(2025, 3, 29, 14, 40, 27, 801, DateTimeKind.Local).AddTicks(2204),
                            UpdatedUser = "SYSTEM"
                        },
                        new
                        {
                            Id = -2,
                            Country = "Unknown",
                            CustomerId = "Unknown",
                            InsertedDate = new DateTime(2025, 3, 29, 14, 40, 27, 801, DateTimeKind.Local).AddTicks(2228),
                            InsertedUser = "SYSTEM",
                            UpdatedDate = new DateTime(2025, 3, 29, 14, 40, 27, 801, DateTimeKind.Local).AddTicks(2229),
                            UpdatedUser = "SYSTEM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
